// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmNZmWTPMaoiCBNQdUnQ50MxJCgCdIeto',
    appId: '1:247890995762:web:3fe7df1168cec2f0292a2b',
    messagingSenderId: '247890995762',
    projectId: 'english-b3eaf',
    authDomain: 'english-b3eaf.firebaseapp.com',
    storageBucket: 'english-b3eaf.firebasestorage.app',
    measurementId: 'G-5N3661LJTH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIa_uLcS-IX9wuI2b5WbgfwTVvm2k9KS0',
    appId: '1:247890995762:android:1fc07d6cd61c9f19292a2b',
    messagingSenderId: '247890995762',
    projectId: 'english-b3eaf',
    storageBucket: 'english-b3eaf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAn9jExq2KMIFdaRw0IEM_flS6RSx1jWVo',
    appId: '1:247890995762:ios:dc5fb20811e04555292a2b',
    messagingSenderId: '247890995762',
    projectId: 'english-b3eaf',
    storageBucket: 'english-b3eaf.firebasestorage.app',
    iosBundleId: 'com.example.englishMongolianWords',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAn9jExq2KMIFdaRw0IEM_flS6RSx1jWVo',
    appId: '1:247890995762:ios:dc5fb20811e04555292a2b',
    messagingSenderId: '247890995762',
    projectId: 'english-b3eaf',
    storageBucket: 'english-b3eaf.firebasestorage.app',
    iosBundleId: 'com.example.englishMongolianWords',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmNZmWTPMaoiCBNQdUnQ50MxJCgCdIeto',
    appId: '1:247890995762:web:196a834023ecbb0a292a2b',
    messagingSenderId: '247890995762',
    projectId: 'english-b3eaf',
    authDomain: 'english-b3eaf.firebaseapp.com',
    storageBucket: 'english-b3eaf.firebasestorage.app',
    measurementId: 'G-QLGCJRGRD6',
  );
}
