// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDe3SZfNP3Yxd2SAssQ8r48rGWooXb_cV4',
    appId: '1:342525381381:web:5b762d99200574feec456c',
    messagingSenderId: '342525381381',
    projectId: 'flashcard-83890',
    authDomain: 'flashcard-83890.firebaseapp.com',
    storageBucket: 'flashcard-83890.firebasestorage.app',
    measurementId: 'G-QMHNVQ64B4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBu6_CHXHyDAQcJIXTRmgC6k_AKgQlrBAA',
    appId: '1:342525381381:android:3a44a5d678fee699ec456c',
    messagingSenderId: '342525381381',
    projectId: 'flashcard-83890',
    storageBucket: 'flashcard-83890.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCM0PVxKVVai2JUzVE3T6-_8KJciqiln2k',
    appId: '1:342525381381:ios:986672579c1268e7ec456c',
    messagingSenderId: '342525381381',
    projectId: 'flashcard-83890',
    storageBucket: 'flashcard-83890.firebasestorage.app',
    iosBundleId: 'com.example.flashcard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCM0PVxKVVai2JUzVE3T6-_8KJciqiln2k',
    appId: '1:342525381381:ios:986672579c1268e7ec456c',
    messagingSenderId: '342525381381',
    projectId: 'flashcard-83890',
    storageBucket: 'flashcard-83890.firebasestorage.app',
    iosBundleId: 'com.example.flashcard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDe3SZfNP3Yxd2SAssQ8r48rGWooXb_cV4',
    appId: '1:342525381381:web:d17ec790ba13007bec456c',
    messagingSenderId: '342525381381',
    projectId: 'flashcard-83890',
    authDomain: 'flashcard-83890.firebaseapp.com',
    storageBucket: 'flashcard-83890.firebasestorage.app',
    measurementId: 'G-EJBR7WQJ1S',
  );
}
